FROM python:3.12-slim

WORKDIR /app

# Install system deps (only if needed)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy only requirements first (for Docker cache)
COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Now copy the rest of the project
COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
